import { layerResult } from "../core/layer-result";
import type { KbolArtifact, LayerResult, RunbookArtifact } from "../core/types";

export function generateRunbook(kbol: KbolArtifact | null): { result: LayerResult; artifact: RunbookArtifact | null } {
  const blockers = kbol ? [] : ["CPO must be active before runbook generation"];
  const artifact: RunbookArtifact | null = kbol
    ? {
        id: `RO-${kbol.cpoId}`,
        actors: ["surgeon", "anesthesiology", "perfusion", "icu", "nursing", "materials"],
      }
    : null;

  return {
    artifact,
    result: layerResult({
      id: "RO",
      name: "Runbook Object",
      status: artifact ? "GENERATED" : "BLOCKED",
      message: artifact ? "Runbook generated by actor" : "Runbook generation blocked",
      blockers,
      critical: blockers.length > 0,
      artifacts: artifact ? { runbook: artifact } : {},
    }),
  };
}
