apiVersion: v1
kind: Service
metadata:
  name: icicso-api
  namespace: icicso-local
  labels:
    app.kubernetes.io/name: icicso-api
    app.kubernetes.io/part-of: icicso
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: icicso-api
  ports:
    - name: http
      port: 3100
      targetPort: http
