apiVersion: v1
kind: Service
metadata:
  name: icicso-frontend
  namespace: icicso-local
  labels:
    app.kubernetes.io/name: icicso-frontend
    app.kubernetes.io/part-of: icicso
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: icicso-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
