apiVersion: v1
kind: Service
metadata:
  name: icicso-parser
  namespace: icicso-local
  labels:
    app.kubernetes.io/name: icicso-parser
    app.kubernetes.io/part-of: icicso
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: icicso-parser
  ports:
    - name: http
      port: 3108
      targetPort: http
