apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: icicso-redis-data
  namespace: icicso-local
  labels:
    app.kubernetes.io/name: icicso-redis
    app.kubernetes.io/part-of: icicso
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
