apiVersion: v1
kind: Secret
metadata:
  name: icicso-postgres-secret
  namespace: icicso-local
  labels:
    app.kubernetes.io/part-of: icicso
type: Opaque
stringData:
  POSTGRES_PASSWORD: replace-with-postgres-password
