apiVersion: v1
kind: Secret
metadata:
  name: icicso-redis-secret
  namespace: icicso-local
  labels:
    app.kubernetes.io/part-of: icicso
type: Opaque
stringData:
  REDIS_PASSWORD: set-only-if-redis-auth-is-enabled
