apiVersion: v1
kind: Secret
metadata:
  name: icicso-app-secret
  namespace: icicso-local
  labels:
    app.kubernetes.io/part-of: icicso
type: Opaque
stringData:
  DATABASE_URL: postgresql://icicso:replace-with-postgres-password@icicso-postgres:5432/icicso_local
  JWT_SECRET: replace-with-long-jwt-secret
  INTERNAL_SERVICE_TOKEN: replace-with-long-internal-service-token
  MINIO_ACCESS_KEY: replace-with-minio-access-key
  MINIO_SECRET_KEY: replace-with-minio-secret-key
